#!/bin/sh

xrdb -merge $HOME/.Xresources & xrdbpid=$!

xset r rate 300 50
setxkbmap -layout us,ir -variant ,pes_keypad -option grp:shifts_toggle -option ctrl:nocaps
killall xcape 2>/dev/null ; xcape -e 'Control_L=Escape'

highdpi=$(grep -F 96 "$HOME/.Xresources")

if [ $hidpi ]; then
  export QT_AUTO_SCREEN_SCALE_FACTOR=1
  export QT_ENABLE_HIGHDPI_SCALING=1
  export GDK_SCALE=2
  export GDK_DPI_SCALE=0.5
fi

unset highdpi

autostart="nm-applet dunst unclutter"

for program in $autostart; do
  pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
