#!/bin/sh

# the following excerpt is from the /etc/X11/xinit/xinitrc
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

highdpi=$(grep -F 96 "$HOME/.Xresources")

if [ $hidpi ]; then
  xrandr --setprovideroutputsource modesetting NVIDIA-0
  xrandr --auto
  . "$HOME/.screenlayout/work.sh"
fi

unset highdpi

if [ -x "$HOME/.xprofile" ] ; then
  . "$HOME/.xprofile"
fi

exec awesome
