#!/bin/sh

# the following excerpt is from the /etc/X11/xinit/xinitrc
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# xrandr --setprovideroutputsource modesetting NVIDIA-0
# xrandr --auto
grep -Fq 96 "$HOME/.Xresources" && . "$HOME/.screenlayout/work.sh"

if [ -x "$HOME/.xprofile" ] ; then
  . "$HOME/.xprofile"
fi

exec awesome
