wsl = false
no-multigrid = false
vsync = false
maximized = false
srgb = false
idle = true
neovim-bin = "/usr/local/bin/nvim" # in reality found dynamically on $PATH if unset
frame = "full"
title-hidden = true
